fourth_pytorch_run